# Copyright 2021, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

name: Android Loader - Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  # Loader release
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle

      - name: Build, sign, and publish AAR
        run: ./maintainer-scripts/build-and-publish-aar-mavencentral.sh
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.ORG_GRADLE_PROJECT_signingKey}}
          ORG_GRADLE_PROJECT_signingKeyId: ${{secrets.ORG_GRADLE_PROJECT_signingKeyId}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.ORG_GRADLE_PROJECT_signingPassword}}
          OSSRH_USER: ${{secrets.OSSRH_USER}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
      - name: Upload bare AAR
        uses: actions/upload-artifact@v2
        with:
          name: AAR and POM
          path: openxr_loader_for_android*
      - name: Upload Maven repo
        uses: actions/upload-artifact@v2
        with:
          name: repo
          path: maintainer-scripts/publish-aar/build/repo/

  # Hello XR
  build-helloxr-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle

      # HelloXR OpenGLES version
      - name: Build HelloXR OpenGLES for Android
        run: |
          cd src/tests/hello_xr
          ./gradlew assembleOpenGLESRelease
      - name: Sign HelloXR OpenGLES Android release
        uses: r0adkll/sign-android-release@349ebdef58775b1e0d8099458af0816dc79b6407
        id: sign_gles
        with:
          releaseDirectory: src/tests/hello_xr/build/outputs/apk/OpenGLES/release
          signingKeyBase64: ${{ secrets.APK_SIGNING_KEY }}
          alias: ${{ secrets.APK_ALIAS }}
          keyStorePassword: ${{ secrets.APK_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.APK_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"
      - name: Upload HelloXR OpenGLES Android
        uses: actions/upload-artifact@v2
        with:
          name: HelloXR OpenGLES Android
          path: ${{ steps.sign_gles.outputs.signedReleaseFile }}

      # HelloXR Vulkan version
      - name: Build HelloXR Vulkan for Android
        run: |
          cd src/tests/hello_xr
          ./gradlew assembleVulkanRelease
      - name: Sign HelloXR Vulkan Android release
        uses: r0adkll/sign-android-release@349ebdef58775b1e0d8099458af0816dc79b6407
        id: sign_vulkan
        with:
          releaseDirectory: src/tests/hello_xr/build/outputs/apk/Vulkan/release
          signingKeyBase64: ${{ secrets.APK_SIGNING_KEY }}
          alias: ${{ secrets.APK_ALIAS }}
          keyStorePassword: ${{ secrets.APK_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.APK_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"
      - name: Upload HelloXR Vulkan Android
        uses: actions/upload-artifact@v2
        with:
          name: HelloXR Vulkan Android
          path: ${{ steps.sign_vulkan.outputs.signedReleaseFile }}
