language: cpp
matrix:
  include:
    # Linux GCC x64
    - os: linux
      name: linux64 GCC 8
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - xorg-dev
            - g++-8
      before_install:
        - eval "CC=gcc-8 && CXX=g++-8"
        # Download and install cmake
        - mkdir $HOME/cmake;
        - export PATH="$HOME/cmake/bin:$PATH";
        - travis_retry wget -q https://cmake.org/files/v3.15/cmake-3.15.1-Linux-x86_64.sh;
        - sh cmake-3.15.1-Linux-x86_64.sh --prefix=$HOME/cmake --exclude-subdir --skip-license;
      script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release -DCI_BUILD=ON .. 
        - cmake --build . --config Release

    # Windows MSVC x86
    - os: windows
      name: win32
      language: shell
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      install: pip3 install --upgrade pip
      script:
        - mkdir -p build
        - cd build
        - cmake  -G "Visual Studio 15 2017" -DCI_BUILD=ON .. 
        - cmake --build . --config Release
    
    # Windows MSVC x64
    - os: windows
      name: win64
      language: shell
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      install: pip3 install --upgrade pip
      script:
        - mkdir -p build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" -DCI_BUILD=ON .. 
        - cmake --build . --config Release
      
    # Windows MSVC x64 Debug
    - os: windows
      name: win64 debug
      language: shell
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      install: pip3 install --upgrade pip
      script:
        - mkdir -p build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" -DCI_BUILD=ON .. 
        - cmake --build . --config Debug
