FetchContent_Declare(
	assimp
	GIT_REPOSITORY	https://github.com/assimp/assimp.git
	GIT_TAG			v5.3.1
	SOURCE_DIR		${CMAKE_CURRENT_SOURCE_DIR}/build/_deps/assimp
	GIT_PROGRESS	true
	GIT_SHALLOW		true
)

FetchContent_GetProperties(assimp)
if(NOT assimp_POPULATED)
	FetchContent_Populate(assimp)
	
	if(USE_SHARED_LIBS)
		set(BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
		set(LLVM_USE_CRT_DEBUG MDd CACHE STRING "" FORCE)
		set(LLVM_USE_CRT_MINSIZEREL MD CACHE STRING "" FORCE)
		set(LLVM_USE_CRT_RELEASE MD CACHE STRING "" FORCE)
		set(LLVM_USE_CRT_RELWITHDEBINFO MD CACHE STRING "" FORCE)
		set(USE_MSVC_RUNTIME_LIBRARY_DLL ON CACHE BOOL "")
		set(USE_STATIC_CRT OFF CACHE BOOL "" FORCE)
	else()
		set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
		set(LLVM_USE_CRT_DEBUG MTd CACHE STRING "" FORCE)
		set(LLVM_USE_CRT_MINSIZEREL MT CACHE STRING "" FORCE)
		set(LLVM_USE_CRT_RELEASE MT CACHE STRING "" FORCE)
		set(LLVM_USE_CRT_RELWITHDEBINFO MT CACHE STRING "" FORCE)
		set(USE_MSVC_RUNTIME_LIBRARY_DLL OFF CACHE BOOL "")
		set(USE_STATIC_CRT ON CACHE BOOL "" FORCE)
	endif()
	
	if(NOT CMAKE_DEBUG_POSTFIX)
	  set(CMAKE_DEBUG_POSTFIX _debug)
	endif()
	if(NOT CMAKE_RELEASE_POSTFIX)
	  set(CMAKE_RELEASE_POSTFIX)
	endif()
	if(NOT CMAKE_MINSIZEREL_POSTFIX)
	  set(CMAKE_MINSIZEREL_POSTFIX _minsizerel)
	endif()
	if(NOT CMAKE_RELWITHDEBINFO_POSTFIX)
	  set(CMAKE_RELWITHDEBINFO_POSTFIX _reldeb)
	endif()
	
	set(ASSIMP_INSTALL OFF CACHE BOOL "" FORCE)
	set(ASSIMP_INJECT_DEBUG_POSTFIX OFF CACHE BOOL "" FORCE)
	set(ASSIMP_INSTALL_PDB OFF CACHE BOOL "" FORCE)

	set(ASSIMP_BUILD_ASSIMP_TOOLS OFF CACHE BOOL "" FORCE)
	set(ASSIMP_BUILD_TESTS OFF CACHE BOOL "" FORCE)
	set(ASSIMP_BUILD_ZLIB ON CACHE BOOL "" FORCE)

	set(ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT OFF CACHE BOOL "" FORCE) 
	set(ASSIMP_BUILD_OBJ_IMPORTER ON CACHE BOOL "" FORCE) 
	set(ASSIMP_BUILD_PLY_IMPORTER ON CACHE BOOL "" FORCE) 
	set(ASSIMP_BUILD_GLTF_IMPORTER ON CACHE BOOL "" FORCE)
	set(ASSIMP_BUILD_FBX_IMPORTER ON CACHE BOOL "" FORCE)
	set(ASSIMP_BUILD_NO_COMPRESSED_X OFF CACHE BOOL "" FORCE)
	set(ASSIMP_BUILD_NO_COMPRESSED_BLEND OFF CACHE BOOL "" FORCE)
	set(ASSIMP_BUILD_NO_COMPRESSED_IFC OFF CACHE BOOL "" FORCE)

	set(ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT OFF CACHE BOOL "" FORCE)
	set(ASSIMP_BUILD_OBJ_EXPORTER OFF CACHE BOOL "" FORCE) 
	set(ASSIMP_BUILD_PLY_EXPORTER ON CACHE BOOL "" FORCE) 
	set(ASSIMP_BUILD_GLTF_EXPORTER OFF CACHE BOOL "" FORCE) # seems to be only the gltf 1.0
	set(ASSIMP_BUILD_FBX_EXPORTER OFF CACHE BOOL "" FORCE) # the binaries are biggezr than ascii ply ...
	set(ASSIMP_BUILD_COLLADA_EXPORTER ON CACHE BOOL "" FORCE)

	set(ASSIMP_LIBRARIES assimp)
	set(ASSIMP_INCLUDE_DIR ${assimp_SOURCE_DIR}/include)
	
	##EXCLUDE_FROM_ALL reject install for this target
	add_subdirectory(${assimp_SOURCE_DIR} EXCLUDE_FROM_ALL)

	if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
		target_compile_options(assimp PRIVATE -Wno-everything) # disable all warnings, since im not maintaining this lib
		target_compile_options(zlibstatic PRIVATE -Wno-everything) # disable all warnings, since im not maintaining this lib
	endif()

	if(USE_SHARED_LIBS)
		set_target_properties(assimp PROPERTIES FOLDER 3rdparty/Shared)
		set_target_properties(zlibstatic PROPERTIES FOLDER 3rdparty/Shared)
		set_target_properties(assimp PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${FINAL_BIN_DIR}")
		set_target_properties(assimp PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${FINAL_BIN_DIR}")
		set_target_properties(assimp PROPERTIES RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${FINAL_BIN_DIR}")
		set_target_properties(assimp PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${FINAL_BIN_DIR}")
	else()
		set_target_properties(assimp PROPERTIES FOLDER 3rdparty/Static)
		set_target_properties(zlibstatic PROPERTIES FOLDER 3rdparty/Static)
	endif()

	include_directories(${ASSIMP_INCLUDE_DIR})
endif()
