include(FetchContent)

include(cmake/NotMaintained/tinyxml2.cmake)
include(cmake/NotMaintained/glad.cmake)

if(USE_SDL)
	include(cmake/NotMaintained/sdl.cmake)
else()
	include(cmake/NotMaintained/glfw.cmake)
endif()

include(cmake/NotMaintained/glm.cmake)
include(cmake/NotMaintained/stb.cmake)
include(cmake/NotMaintained/curl.cmake)
include(cmake/NotMaintained/efsw.cmake)
include(cmake/NotMaintained/assimp.cmake)
include(cmake/NotMaintained/rtmidi.cmake)
include(cmake/NotMaintained/kissfft.cmake)
include(cmake/NotMaintained/alphanum.cmake)
include(cmake/NotMaintained/picojson.cmake)
include(cmake/NotMaintained/miniaudio.cmake)

if(USE_VR)
	include(cmake/NotMaintained/openxr.cmake)
endif()

if (USE_PROFILER_TRACY)
	include(cmake/NotMaintained/tracy.cmake)
	option(USE_CALIBRATED_CONTEXT "Enable Calibrated Context in Tracy for sync cpu/gpu timestamps" OFF)
	if (USE_CALIBRATED_CONTEXT)
		add_definitions(-DENABLE_CALIBRATED_CONTEXT)
	endif()
	add_definitions(-DTRACY_ENABLE)
	add_definitions(-DTRACY_ON_DEMAND)
	add_definitions(-DTRACY_NO_BROADCAST)
	add_definitions(-DTRACY_ONLY_LOCALHOST=1)
endif()