set(IMGUIPACK_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ImGuiPack)
set(IMGUIPACK_LIBRARIES ImGuiPack)

set(USE_IMPLOT ON CACHE BOOL "" FORCE)
set(USE_IMCOOL_BAR ON CACHE BOOL "" FORCE)
set(USE_IM_GRADIENT_HDR OFF CACHE BOOL "" FORCE)
set(USE_IMGUI_FILE_DIALOG ON CACHE BOOL "" FORCE)
set(USE_IM_GUIZMO ON CACHE BOOL "" FORCE)
set(USE_IM_TOOLS ON CACHE BOOL "" FORCE)
set(USE_IMGUI_NODE_EDITOR ON CACHE BOOL "" FORCE)
set(USE_IMGUI_MARKDOW ON CACHE BOOL "" FORCE)
set(USE_IMGUI_COLOR_TEXT_EDIT ON CACHE BOOL "" FORCE)
set(USE_IN_APP_GPU_PROFILER ON CACHE BOOL "" FORCE)

set(IMGUIPACK_USE_STD_FILESYSTEM ON CACHE BOOL "" FORCE)
 
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ImGuiPack)

if(USE_SHARED_LIBS)
	set_target_properties(ImGuiPack PROPERTIES FOLDER Libs/Shared)
else()
	set_target_properties(ImGuiPack PROPERTIES FOLDER Libs/Static)
endif()

set_target_properties(ImGuiPack PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${FINAL_BIN_DIR}")
set_target_properties(ImGuiPack PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${FINAL_BIN_DIR}")
set_target_properties(ImGuiPack PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${FINAL_BIN_DIR}")
