set(RTMIDI_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/rtmidi)
set(RTMIDI_LIBRARIES ${RTMIDI_LIBRARIES} rtmidi)
set(BUILD_TESTING OFF CACHE BOOL "")

add_subdirectory(${RTMIDI_INCLUDE_DIR} EXCLUDE_FROM_ALL)
set_target_properties(${RTMIDI_LIBRARIES} PROPERTIES FOLDER 3rdparty/audio)


